[package]
authors = [
    "Sean Bowe <ewillbefull@gmail.com>",
    "Eirik Ogilvie-Wigley <eowigley@gmail.com>",
    "Jack Grigg <thestr4d@gmail.com>",
    "CPerezz <carlos@dusk.network>"
]
description = "Dusk's fork of the implementation of the Jubjub elliptic curve group"
homepage = "https://github.com/dusk-network/jubjub"
license = "MIT/Apache-2.0"
name = "dusk-jubjub"
repository = "https://github.com/dusk-network/jubjub"
version = "0.12.1"
keywords = ["cryptography", "jubjub", "zk-snarks", "ecc", "elliptic-curve"]
categories =["algorithms", "cryptography", "science", "no-std"]
edition = "2021"
exclude = [".github/workflows/ci.yml", "github/workflows/rust.yml",
".gitignore", 
]

[dependencies]
dusk-bytes = "0.1"
dusk-bls12_381 = {version="0.11", default-features=false}
subtle = {version="^2.3", default-features = false}
rand_core = {version = "0.6", default-features=false}
rkyv = {version = "0.7", optional = true, default-features = false}
bytecheck = {version = "0.6", optional=true, default-features = false}

[dev-dependencies]
rand_xorshift = {version="0.3", default-features = false}
blake2 = "0.9"

[features]
default = ["std"]
std = ["dusk-bls12_381/default"]
rkyv-impl = ["bytecheck", "dusk-bls12_381/rkyv-impl", "rkyv"]
